package dto;

// Generated Feb 22, 2013 7:43:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

/**
 * Cart generated by hbm2java
 */
public class Cart implements java.io.Serializable {

	private Integer id;
	private User user;
	private Set<CartGame> cartGames = new HashSet<CartGame>(0);

	public Cart() {
	}

	public Cart(User user) {
		this.user = user;
	}

	public Cart(Set<CartGame> cartGames) {
	//public Cart(User user, Set<CartGame> cartGames) {
		//this.user = user;
		this.cartGames = cartGames;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set<CartGame> getCartGames() {
		return this.cartGames;
	}
	
	public void addCartGames(CartGame cartGame) {
		cartGames.add(cartGame);
		cartGame.setCart(this);
	}

	public void setCartGames(Set<CartGame> cartGames) {
		this.cartGames = cartGames;
	}
	
	public int getItemsCount() {
		int count = 0;
		for (Iterator<CartGame> iterator = cartGames.iterator(); iterator.hasNext();) {
			CartGame type = (CartGame) iterator.next();
			count += type.getQuantity();
		}
		return count;
	}
	
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof Cart) {
			return id.equals(((Cart) obj).getId());
		}
		return super.equals(obj);
	}

}
