package dto;

// Generated Feb 25, 2013 12:11:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * Credit generated by hbm2java
 */
public class Credit implements java.io.Serializable {

	private String serial;
	private float value;
	private boolean Used ;

	public Credit() {
	}

	public Credit(String serial, int value) {
		this.serial = serial;
		this.value = value;
	}

	public String getSerial() {
		return this.serial;
	}

	public void setSerial(String serial) {
		this.serial = serial;
	}

	public float getValue() {
		return this.value;
	}

	public void setValue(float value) {
		this.value = value;
	}
	public void setUsed(boolean used) {
		Used = used;
	}
	public boolean isUsed() {
		return Used;
	}

}
