package dto;

// Generated Feb 22, 2013 7:43:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Game generated by hbm2java
 */
public class Game implements java.io.Serializable {

	private Integer id;
	private Category category;
	private String name;
	private int quantity;
	private float price;
	private byte[] image;
	private String description;
	private Set<CartGame> cartGames = new HashSet<CartGame>(0);
	private Set<Platform> platforms = new HashSet<Platform>(0);
	private Set<Order> orders = new HashSet<Order>(0);

	public Game() {
	}

	public Game(Category category, String name, int quantity, float price) {
		this.category = category;
		this.name = name;
		this.quantity = quantity;
		this.price = price;
	}

	public Game(Category category, String name, int quantity, float price,
			byte[] image, String description, Set<CartGame> cartGames,
			Set<Platform> platforms, Set<Order> orders) {
		this.category = category;
		this.name = name;
		this.quantity = quantity;
		this.price = price;
		this.image = image;
		this.description = description;
		this.cartGames = cartGames;
		this.platforms = platforms;
		this.orders = orders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<CartGame> getCartGames() {
		return this.cartGames;
	}

	public void setCartGames(Set<CartGame> cartGames) {
		this.cartGames = cartGames;
	}

	public Set<Platform> getPlatforms() {
		return this.platforms;
	}

	public void setPlatforms(Set<Platform> platforms) {
		this.platforms = platforms;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}
	
	@Override
	public boolean equals(Object obj) {
		if(obj instanceof Game) 
			return name.equals(((Game) obj).getName());
		return super.equals(obj);
	}

}
