package dto;

// Generated Feb 22, 2013 7:43:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private Integer id;
	private User user;
	private Game game;
	private int quantity;
	private Date date;

	public Order() {
	}

	public Order(Integer id, User user, Game game, int quantity, Date date) {
		this.id = id;
		this.user = user;
		this.game = game;
		this.quantity = quantity;
		this.date = date;
	}
	
	public Order(User user, Game game, int quantity, Date date) {
		this.user = user;
		this.game = game;
		this.quantity = quantity;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Game getGame() {
		return this.game;
	}

	public void setGame(Game game) {
		this.game = game;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
