package dto;

// Generated Feb 22, 2013 7:43:53 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Platform generated by hbm2java
 */
public class Platform implements java.io.Serializable {

	private Integer id;
	private String name;
	private byte[] image;
	private Set<Game> games = new HashSet<Game>(0);

	public Platform() {
	}

	public Platform(String name) {
		this.name = name;
	}

	public Platform(String name, byte[] image, Set<Game> games) {
		this.name = name;
		this.image = image;
		this.games = games;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public Set<Game> getGames() {
		return this.games;
	}

	public void setGames(Set<Game> games) {
		this.games = games;
	}

}
