package dto;

// Generated Feb 22, 2013 7:43:53 PM by Hibernate Tools 3.4.0.CR1

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	
	private static final long serialVersionUID = -4244439487903095525L;
	
	public static final short USER_TYPE = 0;
	public static final short ADMIN_TYPE = 1;
	
	private Integer id;
	private String name;
	private String password;
	private Date birthday;
	private String job;
	private String email;
	private Float credit;
	private String address;
	private String interests;
	private byte[] image;
	private short type;
	private Cart cart;
	private Set<Order> orders = new HashSet<Order>(0);

	public User() {
	}
	
	public User(String email, String password) {
		this.email = email;
		this.password = password;
	}

	public User(String name, String password, String email, short type) {
		this.name = name;
		this.password = password;
		this.email = email;
		this.type = type;
	}

	public User(String name, String password, Date birthday, String job,
			String email, Float credit, String address, String interests,
			byte[] image, short type, Cart cart, Set<Order> orders) {
		this.name = name;
		this.password = password;
		this.birthday = birthday;
		this.job = job;
		this.email = email;
		this.credit = credit;
		this.address = address;
		this.interests = interests;
		this.image = image;
		this.type = type;
		this.cart = cart;
		this.orders = orders;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthday() {
		return this.birthday;
	}
	
	public String getBirthdayStr() {
		if(birthday == null)
			return null;
		return new SimpleDateFormat("yyyy-mm-dd").format(birthday);
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Float getCredit() {
		return this.credit;
	}

	public void setCredit(Float credit) {
		this.credit = credit;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getInterests() {
		return this.interests;
	}

	public void setInterests(String interests) {
		this.interests = interests;
	}

	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public Cart getCart() {
		return cart;
	}
	
	public void setCart(Cart cart) {
		this.cart = cart;
	}

	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
